### ISSUE TITLE
I only have gpt3.5 , how could I use it

### ISSUE THREAD

**Issue by hxsmyxh** [seanpixel/Teenage-AGI#14]
May I know

**Comment by seanpixel** [comment]
You can either change line 18 of [agent.py](https://github.com/seanpixel/Teenage-AGI/blob/main/agent.py) to OPENAI_MODEL =  "gpt-3.5-turbo" or set the environment variable "OPENAI_MODEL" to "gpt-3.5-turbo" in the .env file
